name: autoCBH
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23
  - pandas=1.4
  - rdkit=2022.09
  - notebook
  - graph-tool-base
  - python-igraph=0.9.11
  - openpyxl
  - easydict
  - yaml
  - pyyaml
  - networkx
  - pygraphviz=1.9
  - matplotlib
  - pip
  - pip:
    - pytest
    - tqdm